/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package gui;

import javax.swing.JOptionPane;


public class mdiPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form mdiPrincipal
     */
    public mdiPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator9 = new javax.swing.JSeparator();
        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        ToolBar1 = new javax.swing.JToolBar();
        btnHabitaciones = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        btnClientes = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        btnSalir = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnu_Archivo_Habitaciones = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnu_Archivo_Clientes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnu_Archivo_RentaHab = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnu_Archivo_ReporFact = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnu_Archivo_Salir = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        mnuVentana = new javax.swing.JMenu();
        mnu_Ventana_OpcionVentan = new javax.swing.JMenu();
        mnu_Ventana_OpcVentana_OpcionParal = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnu_Ventana_OpcVentana_OpcionCasc = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnu_Ventana_Cerrar = new javax.swing.JMenu();
        mnu_Ventana_Cerrar_CerrarActu = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnu_Ventana_Cerrar_CerrarTods = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnu_Ayuda_OpcContenido = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mnu_Ayuda_OpcAcercade = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menú Principal");

        escritorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final.png"))); // NOI18N
        escritorio.add(jLabel1);
        jLabel1.setBounds(-370, 80, 1980, 710);

        ToolBar1.setRollover(true);

        btnHabitaciones.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Habitaciones.png"))); // NOI18N
        btnHabitaciones.setText("Habitaciones");
        btnHabitaciones.setFocusable(false);
        btnHabitaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHabitaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitacionesActionPerformed(evt);
            }
        });
        ToolBar1.add(btnHabitaciones);
        ToolBar1.add(jSeparator11);

        btnClientes.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientes.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setFocusable(false);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        ToolBar1.add(btnClientes);
        ToolBar1.add(jSeparator12);

        btnSalir.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        ToolBar1.add(btnSalir);

        escritorio.add(ToolBar1);
        ToolBar1.setBounds(-10, -3, 1550, 80);

        menuBar.setBackground(new java.awt.Color(0, 204, 153));
        menuBar.setToolTipText("Menú Principal");

        mnuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu Principal.png"))); // NOI18N
        mnuArchivo.setMnemonic('f');
        mnuArchivo.setText("Archivo");
        mnuArchivo.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N

        mnu_Archivo_Habitaciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnu_Archivo_Habitaciones.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        mnu_Archivo_Habitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Habitaciones.png"))); // NOI18N
        mnu_Archivo_Habitaciones.setText("Habitaciones");
        mnu_Archivo_Habitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_Archivo_HabitacionesActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnu_Archivo_Habitaciones);
        mnuArchivo.add(jSeparator1);

        mnu_Archivo_Clientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnu_Archivo_Clientes.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        mnu_Archivo_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientes.png"))); // NOI18N
        mnu_Archivo_Clientes.setText("Clientes");
        mnu_Archivo_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_Archivo_ClientesActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnu_Archivo_Clientes);
        mnuArchivo.add(jSeparator2);

        mnu_Archivo_RentaHab.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnu_Archivo_RentaHab.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        mnu_Archivo_RentaHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentaHab.png"))); // NOI18N
        mnu_Archivo_RentaHab.setText("Renta de Habitaciones");
        mnu_Archivo_RentaHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_Archivo_RentaHabActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnu_Archivo_RentaHab);
        mnuArchivo.add(jSeparator3);

        mnu_Archivo_ReporFact.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnu_Archivo_ReporFact.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        mnu_Archivo_ReporFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/facturacion.png"))); // NOI18N
        mnu_Archivo_ReporFact.setText("Reportes de Facturación");
        mnu_Archivo_ReporFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_Archivo_ReporFactActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnu_Archivo_ReporFact);
        mnuArchivo.add(jSeparator4);

        mnu_Archivo_Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mnu_Archivo_Salir.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        mnu_Archivo_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        mnu_Archivo_Salir.setText("Salir");
        mnu_Archivo_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_Archivo_SalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnu_Archivo_Salir);
        mnuArchivo.add(jSeparator10);

        menuBar.add(mnuArchivo);

        mnuVentana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menuVentana.png"))); // NOI18N
        mnuVentana.setMnemonic('f');
        mnuVentana.setText("Ventana");
        mnuVentana.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N

        mnu_Ventana_OpcionVentan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventana (2).png"))); // NOI18N
        mnu_Ventana_OpcionVentan.setText("Opción de Ventana");
        mnu_Ventana_OpcionVentan.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N

        mnu_Ventana_OpcVentana_OpcionParal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnu_Ventana_OpcVentana_OpcionParal.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        mnu_Ventana_OpcVentana_OpcionParal.setText("Opción en Paralelo");
        mnu_Ventana_OpcionVentan.add(mnu_Ventana_OpcVentana_OpcionParal);
        mnu_Ventana_OpcionVentan.add(jSeparator6);

        mnu_Ventana_OpcVentana_OpcionCasc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnu_Ventana_OpcVentana_OpcionCasc.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        mnu_Ventana_OpcVentana_OpcionCasc.setText("Opción en Cascada");
        mnu_Ventana_OpcionVentan.add(mnu_Ventana_OpcVentana_OpcionCasc);

        mnuVentana.add(mnu_Ventana_OpcionVentan);
        mnuVentana.add(jSeparator5);

        mnu_Ventana_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        mnu_Ventana_Cerrar.setText("Cerrar");
        mnu_Ventana_Cerrar.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N

        mnu_Ventana_Cerrar_CerrarActu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnu_Ventana_Cerrar_CerrarActu.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        mnu_Ventana_Cerrar_CerrarActu.setText("Cerrar Actual");
        mnu_Ventana_Cerrar.add(mnu_Ventana_Cerrar_CerrarActu);
        mnu_Ventana_Cerrar.add(jSeparator7);

        mnu_Ventana_Cerrar_CerrarTods.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnu_Ventana_Cerrar_CerrarTods.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        mnu_Ventana_Cerrar_CerrarTods.setText("Cerrar Todas");
        mnu_Ventana_Cerrar.add(mnu_Ventana_Cerrar_CerrarTods);

        mnuVentana.add(mnu_Ventana_Cerrar);

        menuBar.add(mnuVentana);

        mnuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ayuda.png"))); // NOI18N
        mnuAyuda.setMnemonic('f');
        mnuAyuda.setText("Ayuda");
        mnuAyuda.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N

        mnu_Ayuda_OpcContenido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnu_Ayuda_OpcContenido.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        mnu_Ayuda_OpcContenido.setText("Opción Contenido...");
        mnuAyuda.add(mnu_Ayuda_OpcContenido);
        mnuAyuda.add(jSeparator8);

        mnu_Ayuda_OpcAcercade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnu_Ayuda_OpcAcercade.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        mnu_Ayuda_OpcAcercade.setText("Opción Acerca de...");
        mnuAyuda.add(mnu_Ayuda_OpcAcercade);
        mnuAyuda.add(jSeparator13);

        menuBar.add(mnuAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1539, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
        );

        escritorio.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnu_Archivo_ReporFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_Archivo_ReporFactActionPerformed
        // Se crea el objeto       
        ReporteFacturas h4 = new ReporteFacturas();
        // se añade al jDesktopPane
        escritorio.add(h4);
        //se muestra en pantalla
        h4.show();
    
    }//GEN-LAST:event_mnu_Archivo_ReporFactActionPerformed

    private void mnu_Archivo_HabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_Archivo_HabitacionesActionPerformed
        // Se crea el objeto       
        Habitaciones h1 = new Habitaciones();
        // se añade al jDesktopPane
        escritorio.add(h1);
        //se muestra en pantalla
        h1.show();
    
    }//GEN-LAST:event_mnu_Archivo_HabitacionesActionPerformed

    private void mnu_Archivo_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_Archivo_ClientesActionPerformed
        // Se crea el objeto       
        Clientes h2 = new Clientes();
        // se añade al jDesktopPane
        escritorio.add(h2);
        //se muestra en pantalla
        h2.show();
    }//GEN-LAST:event_mnu_Archivo_ClientesActionPerformed

    private void mnu_Archivo_RentaHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_Archivo_RentaHabActionPerformed
        // Se crea el objeto       
        RentaHabitaciones h3 = new RentaHabitaciones();
        // se añade al jDesktopPane
        escritorio.add(h3);
        //se muestra en pantalla
        h3.show();
    }//GEN-LAST:event_mnu_Archivo_RentaHabActionPerformed

    private void mnu_Archivo_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_Archivo_SalirActionPerformed
         int resp=0;
       resp=JOptionPane.showConfirmDialog(rootPane, "¿Realmente desea salir?","Salir",
               JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (resp==JOptionPane.YES_OPTION) 
            System.exit(1);//Ciere el programa
    }//GEN-LAST:event_mnu_Archivo_SalirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
                int resp=0;
       resp=JOptionPane.showConfirmDialog(rootPane, "¿Realmente desea salir de toda la aplicación?","Salir",
               JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (resp==JOptionPane.YES_OPTION) 
            System.exit(1);//Ciere el programa
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
             // Se crea el objeto       
        Clientes h2 = new Clientes();
        // se añade al jDesktopPane
        escritorio.add(h2);
        //se muestra en pantalla
        h2.show();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitacionesActionPerformed
              // Se crea el objeto       
        Habitaciones h1 = new Habitaciones();
        // se añade al jDesktopPane
        escritorio.add(h1);
        //se muestra en pantalla
        h1.show();
    
    }//GEN-LAST:event_btnHabitacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mdiPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar ToolBar1;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnHabitaciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuVentana;
    private javax.swing.JMenuItem mnu_Archivo_Clientes;
    private javax.swing.JMenuItem mnu_Archivo_Habitaciones;
    private javax.swing.JMenuItem mnu_Archivo_RentaHab;
    private javax.swing.JMenuItem mnu_Archivo_ReporFact;
    private javax.swing.JMenuItem mnu_Archivo_Salir;
    private javax.swing.JMenuItem mnu_Ayuda_OpcAcercade;
    private javax.swing.JMenuItem mnu_Ayuda_OpcContenido;
    private javax.swing.JMenu mnu_Ventana_Cerrar;
    private javax.swing.JMenuItem mnu_Ventana_Cerrar_CerrarActu;
    private javax.swing.JMenuItem mnu_Ventana_Cerrar_CerrarTods;
    private javax.swing.JMenuItem mnu_Ventana_OpcVentana_OpcionCasc;
    private javax.swing.JMenuItem mnu_Ventana_OpcVentana_OpcionParal;
    private javax.swing.JMenu mnu_Ventana_OpcionVentan;
    // End of variables declaration//GEN-END:variables

}
